server:
  port: 8082

spring:
  application:
    name: x-payment-adapter-app

  kafka:
    bootstrap-servers: localhost:9093

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: xpayment-adapter-request-consumers
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring.json.use.type.headers: false
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: "com.iprody.xpayment.adapter.app.async.XPaymentAdapterRequestMessage"

    listener:
      ack-mode: manual
      concurrency: 1

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        missing-queues-fatal: false


  app:
    kafka:
      topics:
        xpayment-adapter:
          request: xpayment-adapter.requests
          response: xpayment-adapter.responses

    rabbitmq:
      exchange-name: payment-state-check-exchange
      queue-name: payment-state-check-queue
      virtual-host: /
      max-retries: 60
      interval-ms: 60000
      dlx-exchange-name: payments.dlx
      dlx-routing-key: payments.dead


x-payment-api:
  client:
     url: http://localhost:9999
     username: paymentAgentIprody
     password: iprodyTestPassword0123
     account: paymentAgentIprodyApiToken


logging:
  level:
    org.springframework.amqp: DEBUG
    com.iprody.xpayment.adapter: DEBUG